### ISSUE TITLE
为什么上传失败，本地/七牛都不行，错误500

### ISSUE THREAD

**Issue by Ryongyon** [helloxz/xz-pic#1]
POST http://md.ryongyon.com/tc/qnupload.php 500 (Internal Server Error)
POST http://md.ryongyon.com/tc/qnupload.php 500 (Internal Server Error)

七牛的AK，SK配置无误

**Comment by helloxz** [comment]
您好，这个应该是您PHP版本太低了，要求PHP >= 5.6，在php.ini开启详细报错可查看到，应该是exif_imagetype()这个函数导致。

**Comment by Ryongyon** [comment]
@helloxz 唔...看了一下，果然如此 因为我没安装那个扩展，谢谢你
